---
- name: Install Nginx
  hosts: all
  become: true
  
  tasks:
    - name: update package
      apt:
        update_cache: yes 
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: start nginx server
      service:
        name: nginx
        state: started
        enabled: yes  
