---
- name: Uninstall Nginx
  hosts: all
  become: yes

  tasks:
    - name: Uninstall Nginx
      apt:
        name: nginx
        state: absent
    - name: stop
      service:
        name: nginx
        state: stopped
        enabled: no
        
